version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: crypto-balance
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}

  crypto-balance:
    build: .
    image: crypto-balance
    restart: unless-stopped
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8000
      APPLICATION_PASSWORD: ${APPLICATION_PASSWORD}
      BINANCE_API_KEY: ${BINANCE_API_KEY}
      BINANCE_API_SECRET: ${BINANCE_API_SECRET}
      NOMICS_API_KEY: ${NOMICS_API_KEY}
      MONGODB_HOST: mongo
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 80:8000
